from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Set up order tables in the database'

    def handle(self, *args, **options):
        with connection.cursor() as cursor:
            # Drop existing tables if they exist
            cursor.execute("""
                DROP TABLE IF EXISTS "store_orderitem" CASCADE;
                DROP TABLE IF EXISTS "store_order" CASCADE;
            """)
            
            # Create Order table
            cursor.execute("""
                CREATE TABLE "store_order" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_number" varchar(20) NOT NULL UNIQUE,
                    "status" varchar(20) NOT NULL,
                    "total_amount" numeric(10,2) NOT NULL,
                    "shipping_address" text NOT NULL,
                    "phone_number" varchar(15) NOT NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "notes" text NULL,
                    "customer_id" integer NOT NULL
                );
            """)
            
            # Create OrderItem table
            cursor.execute("""
                CREATE TABLE "store_orderitem" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "quantity" integer NOT NULL,
                    "price" numeric(10,2) NOT NULL,
                    "order_id" bigint NOT NULL,
                    "product_id" bigint NOT NULL
                );
            """)
            
            # Add foreign key constraints
            cursor.execute("""
                ALTER TABLE "store_order" ADD CONSTRAINT "store_order_customer_id_fkey" 
                FOREIGN KEY ("customer_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
                
                ALTER TABLE "store_orderitem" ADD CONSTRAINT "store_orderitem_order_id_fkey" 
                FOREIGN KEY ("order_id") REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED;
                
                ALTER TABLE "store_orderitem" ADD CONSTRAINT "store_orderitem_product_id_fkey" 
                FOREIGN KEY ("product_id") REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED;
            """)
            
            self.stdout.write(
                self.style.SUCCESS('Successfully created order tables')
            ) 