# Generated by Django 5.2.3 on 2025-07-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
