# Generated by Django 5.2.4 on 2025-07-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20250727_1954'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE store_product 
            ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE store_product 
            DROP COLUMN IF EXISTS stock_quantity;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE store_product 
            ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 10;
            """,
            reverse_sql="""
            ALTER TABLE store_product 
            DROP COLUMN IF EXISTS low_stock_threshold;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE store_product 
            ADD COLUMN IF NOT EXISTS is_in_stock BOOLEAN DEFAULT TRUE;
            """,
            reverse_sql="""
            ALTER TABLE store_product 
            DROP COLUMN IF EXISTS is_in_stock;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE store_product 
            ADD COLUMN IF NOT EXISTS last_stock_update TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
            ALTER TABLE store_product 
            DROP COLUMN IF EXISTS last_stock_update;
            """
        ),
    ] 