# Generated by Django 5.2.4 on 2025-07-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_last_stock_update_order_orderitem'),
    ]

    operations = [
        migrations.RunSQL(
            # Create Order table
            """
            CREATE TABLE IF NOT EXISTS "store_order" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "order_number" varchar(20) NOT NULL UNIQUE,
                "status" varchar(20) NOT NULL,
                "total_amount" numeric(10,2) NOT NULL,
                "shipping_address" text NOT NULL,
                "phone_number" varchar(15) NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "notes" text NULL,
                "customer_id" integer NOT NULL
            );
            """,
            # Reverse SQL
            """
            DROP TABLE IF EXISTS "store_order";
            """
        ),
        migrations.RunSQL(
            # Create OrderItem table
            """
            CREATE TABLE IF NOT EXISTS "store_orderitem" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "quantity" integer NOT NULL,
                "price" numeric(10,2) NOT NULL,
                "order_id" bigint NOT NULL,
                "product_id" bigint NOT NULL
            );
            """,
            # Reverse SQL
            """
            DROP TABLE IF EXISTS "store_orderitem";
            """
        ),
        migrations.RunSQL(
            # Add foreign key constraints
            """
            ALTER TABLE "store_order" ADD CONSTRAINT "store_order_customer_id_fkey" 
            FOREIGN KEY ("customer_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
            
            ALTER TABLE "store_orderitem" ADD CONSTRAINT "store_orderitem_order_id_fkey" 
            FOREIGN KEY ("order_id") REFERENCES "store_order" ("id") DEFERRABLE INITIALLY DEFERRED;
            
            ALTER TABLE "store_orderitem" ADD CONSTRAINT "store_orderitem_product_id_fkey" 
            FOREIGN KEY ("product_id") REFERENCES "store_product" ("id") DEFERRABLE INITIALLY DEFERRED;
            """,
            # Reverse SQL
            """
            ALTER TABLE "store_order" DROP CONSTRAINT IF EXISTS "store_order_customer_id_fkey";
            ALTER TABLE "store_orderitem" DROP CONSTRAINT IF EXISTS "store_orderitem_order_id_fkey";
            ALTER TABLE "store_orderitem" DROP CONSTRAINT IF EXISTS "store_orderitem_product_id_fkey";
            """
        ),
    ]
